
# Config for local testing with Wrangler environment

# See also:
# https://developers.cloudflare.com/workers/wrangler/configuration/
# https://developers.cloudflare.com/workers/wrangler/configuration/#local-environments

name = "durabledocs"
compatibility_date = "2022-09-30"
minify = true

main = "./worker/index.ts"
tsconfig = "./tsconfig.json"

# # This may not work in other development environments
# kv_namespaces = [
#   { binding = "DURABLE_DOC_KV", id = "b392d03c80b443bb89b00c85482a9976", preview_id = "2f239bae7ecc4d6bb640aad24297f085" }
# ]

[dev]
  port = 8088

# https://developers.cloudflare.com/workers/learning/using-durable-objects
[durable_objects]
  bindings = [
    { name = "DURABLE_DOC_DATA", class_name = "DurableDocData" }
  ]

[[migrations]]
  tag = "v1" # Should be unique for each entry
  new_classes = ["DurableDocData"]
