
# Config for local testing with Wrangler environment

# See also:
# https://developers.cloudflare.com/workers/wrangler/configuration/
# https://developers.cloudflare.com/workers/wrangler/configuration/#local-environments

name = "durable-documents"
compatibility_date = "2022-11-30"
minify = true

main = "./src/index.ts"
tsconfig = "./tsconfig.json"

[dev]
  port = 8088

# https://developers.cloudflare.com/workers/learning/using-durable-objects
[durable_objects]
  bindings = [
    { name = "THING", class_name = "Thing" },
    { name = "USER", class_name = "User" },
    { name = "ROOM", class_name = "Room" },
    { name = "LIST", class_name = "List" },
  ]

[[migrations]]
  tag = "v1" # Should be unique for each entry
  new_classes = ["Thing"]
